//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIsparn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPAEntitiesrn : DbContext
    {
        public SPAEntitiesrn()
            : base("name=SPAEntitiesrn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHINHANH> CHINHANHs { get; set; }
        public virtual DbSet<CHITIET_GIUONG> CHITIET_GIUONG { get; set; }
        public virtual DbSet<CHITIET_LICHHEN> CHITIET_LICHHEN { get; set; }
        public virtual DbSet<DATTRUOC> DATTRUOCs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<GIUONG> GIUONGs { get; set; }
        public virtual DbSet<LICHHEN> LICHHENs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TTCANHAN> TTCANHANs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
